config/routes.rb
Rails.application.routes.draw do
  root to: 'messages#index'
  resources :messages, :only => [:index, :new, :create, :show]
end

app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_message

  private

  def send_message
    begin
    response = RestClient::Request.new(
    :method => :post,
    :url => 'https://api.twilio.com/2010-04-01/Accounts/AC89f9295f454ac3921f0a8d055aa04b35/Messages.json',
    :user => ENV['TWILIO_ACCOUNT_SID'],
    :password => ENV['TWILIO_AUTH_TOKEN'],
    :payload => { :Body => body,
                  :To => to,
                  :From => from }
      ).execute
    rescue
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "Your message was sent!"
      redirect_to messages_path
    else
      render 'new'
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  private

  def message_params
    params.require(:message).permit(:to, :from, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwilioClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:notice] %>
<%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<h1>Messages</h1>

<ul>
  <% @messages.each do |message| %>
  <li><%= link_to message.id, message_path(message) %></li>
  <% end %>
</ul>

<%= link_to "New Message", new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<% if @message.errors.any? %>
  <p>something went wrong:</p>
  <ul>
    <% @message.errors.full_messages.each do |message| %>
      <li><%= message %></li>
  <% end %>
 </ul>
 <% end %>

<%= form_for @message do |f| %>
  <%= f.label :to %>
  <%= f.text_field :to %>
  <%= f.label :from %>
  <%= f.text_field :from %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit %>
<% end %>